[features]
seeds = false
skip-lint = false
[programs.devnet]
# must change after build
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"


[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
wallet = "/home/baris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
